#include<iostream>
#include<math.h>
using namespace std;

int main()
{
    
    int result1,result2, result3,result4,result5,result6;
    
    result1 = ceil(1.2356);
    result2 = sqrt(16);
    result3 = pow(4 , 2); // a ni 3 ghhat --> 12 x 12 x 12 
    result4 = floor(4.2745);
    result5 = abs(-20);
    result6 = round(5.690);
    cout<<"Result of Ceil  --> "<<result1<<endl;
    cout<<"Result of sqrt  --> "<<result2<<endl; 
    cout<<"RESULT OF pow   --> "<<result3<<endl;
    cout<<"RESULT OF floor --> "<<result4<<endl;
    cout<<"RESULT OF abc   --> "<<result5<<endl;
    cout<<"RESULT OF round --> "<<result6<<endl;
    
return 0;
}
